# Stage 1: Build the React app
FROM node:18-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

# ✅ Fix OpenSSL issue
ENV NODE_OPTIONS=--openssl-legacy-provider

COPY . .
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx

COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
