version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  build-frontend:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Build and Push Frontend Docker Image
          command: |
            docker build -t kuzan0069/dream-frontend ./frontend
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push kuzan0069/dream-frontend
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Z4A+Ef7DJZ3N5AtxlC9ISZK/wS6owpq10wDCPtxhTyw"
      - run:
          name: Deploy Frontend on EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_HOST \<< 'EOF'
              docker pull kuzan0069/dream-frontend
              docker compose up -d --no-deps frontend
            EOF

  build-backend:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Build and Push Backend Docker Image
          command: |
            docker build -t kuzan0069/dream-backend ./backend
            echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
            docker push kuzan0069/dream-backend
      - add_ssh_keys:
          fingerprints:
            - "SHA256:Z4A+Ef7DJZ3N5AtxlC9ISZK/wS6owpq10wDCPtxhTyw"
      - run:
          name: Deploy Backend on EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_HOST \<< 'EOF'
              docker pull kuzan0069/dream-backend
              docker compose up -d --no-deps backend
            EOF

workflows:
  deploy-changed-services:
    jobs:
      - build-frontend:
          filters:
            branches:
              only:
                - main
      - build-backend:
          filters:
            branches:
              only:
                - main
